services:
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  webhook-service:
    image: webhook-service:latest
    build: ./webhook-service
    expose:
      - "8000"           # IMPORTANT: no host port
    volumes:
      - ./logs:/app/logs
    environment:
      MONGODB_URL: ${MONGODB_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('127.0.0.1',8000))"]
      interval: 10s
      timeout: 3s
      retries: 5

  celery-worker:
    image: webhook-service:latest
    volumes:
      - ./logs:/app/logs
    environment:
      MONGODB_URL: ${MONGODB_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      DOWNSTREAM_URL: ${DOWNSTREAM_URL}
    depends_on:
      webhook-service:
        condition: service_healthy
    command: celery -A app.tasks worker --loglevel=info

  downstream-service:
    build: ./downstream-service
    expose:
      - "8001"
    volumes:
      - ./logs:/app/logs
    environment:
      REDIS_URL: ${REDIS_URL}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('127.0.0.1',8001))"]
      interval: 10s
      timeout: 3s
      retries: 5

  gateway:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./webhook-service/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      webhook-service:
        condition: service_healthy

  downstream-gateway:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./downstream-service/nginx-downstream.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      downstream-service:
        condition: service_healthy
